[default]

[default.security]
# Set secret key in .secrets.toml
# SECRET_KEY = ""
ALGORITHM = "HS384"
ACCESS_TOKEN_EXPIRE_MINUTES = 30
REFRESH_TOKEN_EXPIRE_MINUTES = 600

[default.server]
port = 8000
host = "127.0.0.1"
log_level = "info"
reload = false

[default.db]
uri = "@jinja sqlite:///{{ this.current_env | lower }}.db"
connect_args = {check_same_thread=false}
echo = false

[default.replay]
max_file_size = 5242880 # Max replay file size in bytes. Default is 5MB
temp_workdir = "/tmp/wows-karma/minimap" # Temporary directory for replay processing
fps = 15 # Frames per second for replay processing
quality = 5 # Quality of the output video. 1 is the lowest quality, 9 is the highest