name: Build & Package Web App

on:
  workflow_call:
    inputs:
      build_configuration:
        description: 'Build Configuration'
        type: string
        required: true
      artifact_name:
        description: 'Artifact Name'
        type: string
        required: false
        default: 'wowskarma_app'  

permissions:
  contents: read
  packages: read

jobs:
  # Build angular app
  build-web:
    name: Build Web App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install dependencies
      working-directory: wowskarma.app
      run: npm install

    - name: Build Angular app
      working-directory: wowskarma.app
      run: ng build --configuration=${{ inputs.build_configuration }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: ./wowskarma.app/dist