name: Deploy to Server

on:
  push:
    branches:
      - main
      - develop

permissions: 
  contents: read
  packages: read
  deployments: write

jobs:
  # First: Make sure dev build ran fine.
  build-test-solution:
    name: Build & Test Solution
    uses: Nodsoft/workflows/.github/workflows/build-dotnet.yml@main
    with:
      dotnet-version: '8.0'
      configuration: 'Release'
      project-file: 'WoWS-Karma.sln'
  
  # Build & Package API & Web from 'build-package-api.yml' and 'build-package-web.yml'.
  build-package-api: 
    name: Build & Package API
    needs: build-test-solution
    uses: Nodsoft/workflows/.github/workflows/package-dotnet.yml@main
    strategy: &build-strategy
      matrix: 
        configuration: ['production', 'preview']
    with:
      dotnet-version: '8.0'
      configuration: ${{ matrix.configuration }}
      project-file: 'WowsKarma.Api/WowsKarma.Api.csproj'
      artifact-name: 'wowskarma_api_${{ matrix.configuration }}'

  build-package-web:
    name: Build & Package Web App
    needs: build-test-solution
    uses: ./.github/workflows/build-package-web.yml
    strategy: *build-strategy
    with:
      build_configuration: ${{ matrix.configuration }}
      artifact_name: 'wowskarma_app_${{ matrix.configuration }}'

  
  deploy-preview: &deploy-job
    name: Deploy to Preview
    environment: 
        name: preview
        url: https://preview.wows-karma.com/
    needs: 
      - build-package-api
      - build-package-web    
    strategy:
      matrix:
        artifact: [
          { name_pre: 'wowskarma_api', path: './api' },
          { name_pre: 'wowskarma_app', path: './web' }
        ]
    uses: Nodsoft/workflows/.github/workflows/package-dotnet.yml@main
    with: 
      artifact_name: ${{ matrix.artifact.name_pre }}_${{ inputs.configuration }}
      artifact_path: ${{ matrix.artifact.path }}
      host: ${{ secrets.SSH_HOST }}
      user: ${{ secrets.SSH_USER }}
      private_key: ${{ secrets.SSH_PRIVATEKEY }}
      remote_path: ${{ secrets.SSH_DEPLOYPATH }}
      post_deploy_cmd: ${{ secrets.SSH_CMD_RESTART_API }}

  deploy-live:
    <<: *deploy-job
    name: Deploy to Live
    environment: 
        name: live
        url: https://wows-karma.com/
    needs: 
      - deploy-preview