name: .NET Build & Test

permissions: 
  contents: read

env:
  SOLUTION: 'WoWS-Karma.sln'

on:
  - push
  - pull_request
  - workflow_call

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    #    include-prerelease: true

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION }}

    - name: Build
      run: dotnet build --no-restore ${{ env.SOLUTION }}

    - name: Test
      run: dotnet test --no-build ${{ env.SOLUTION }}
