name: Push Minimap API Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  release_dockerhub:
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push to DockerHub 
      run: docker push wowskarma_api_minimap:tag

  release_ghcr:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GHCR
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to GHCR
      run: | 
        docker tag wowskarma_api_minimap:tag ghcr.io/${{ github.repository }}/wowskarma_api_minimap:tag
        docker push ghcr.io/${{ github.repository }}/wowskarma_api_minimap:tag