name: Build Minimap API Docker Image

on:
  push:
    paths:
      - 'wowskarma_api_minimap/**'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -f wowskarma_api_minimap/Dockerfile.dev -t wowskarma_api_minimap:tag .